import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { Header } from './layout/Header/Header';
import { Sidebar } from './layout/Sidebar/Sidebar';
import { Footer } from './layout/Footer/Footer';
import { TopLevelCategory } from '@/interfaces/page.interface';
import { getMenu } from '@/api/menu';
import { Up } from './components/Up/Up';
import "./globals.css";
import { MenuItem } from '@/interfaces/menu.interface';
import { SkipLink } from './components/SkipLink/SkipLink';

const notoSansKR = Noto_Sans_KR({
  weight: ['100', '200', '400', '600', '700', '800'],
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Our project Top App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const menu = await getMenu(TopLevelCategory.Courses);

  return (
    <html lang="en">
      <body className={`${notoSansKR.variable}`}>
        <div className={'wrapper'}>
          <SkipLink />
          <Header menu={menu as MenuItem[]} firstCategory={TopLevelCategory.Courses} className={'header'} />
          <Sidebar menu={menu as MenuItem[]} firstCategory={TopLevelCategory.Courses} className={'sidebar'} />
          <main className={'body'}>
            {children}
          </main>
          <Footer className={'footer'} />
          <Up />
        </div>
      </body>
    </html>
  );
}

